"""empty message

Revision ID: 9a3a7ce97867
Revises: dd62ae9caddb
Create Date: 2020-09-02 18:48:46.666449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3a7ce97867'
down_revision = 'dd62ae9caddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encuestador', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=True),
    sa.Column('orientacion_sexual', sa.String(length=30), nullable=True),
    sa.Column('ultimo_consumo_psicotropicas', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_periodo_menstrual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_tatuaje', sa.DateTime(timezone=True), nullable=True),
    sa.Column('donante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donante_id'], ['donante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muestra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tiene_enfermedad', sa.Boolean(), nullable=True),
    sa.Column('bioanalista', sa.String(length=30), nullable=True),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muestra')
    op.drop_table('visita')
    # ### end Alembic commands ###
