"""empty message

Revision ID: dd62ae9caddb
Revises: 
Create Date: 2020-09-01 21:03:04.946284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd62ae9caddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=14), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hepatitis', sa.Boolean(), nullable=True),
    sa.Column('VIH', sa.Boolean(), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('RH_positivo', sa.Boolean(), nullable=True),
    sa.Column('sangre_tipo', sa.String(length=2), nullable=True),
    sa.Column('donante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donante_id'], ['donante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfil')
    op.drop_table('donante')
    # ### end Alembic commands ###
