"""empty message

Revision ID: fa7bb4c58afc
Revises: 
Create Date: 2020-09-08 18:26:40.346600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7bb4c58afc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=14), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hepatitis', sa.Boolean(), nullable=True),
    sa.Column('VIH', sa.Boolean(), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('RH_positivo', sa.Boolean(), nullable=True),
    sa.Column('sangre_tipo', sa.String(length=2), nullable=True),
    sa.Column('donante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donante_id'], ['donante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encuestador', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=True),
    sa.Column('orientacion_sexual', sa.String(length=30), nullable=True),
    sa.Column('ultimo_consumo_psicotropicas', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_periodo_menstrual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_tatuaje', sa.DateTime(timezone=True), nullable=True),
    sa.Column('donante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donante_id'], ['donante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muestra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tiene_enfermedad', sa.Boolean(), nullable=True),
    sa.Column('bioanalista', sa.String(length=30), nullable=True),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muestra')
    op.drop_table('visita')
    op.drop_table('perfil')
    op.drop_table('donante')
    # ### end Alembic commands ###
